### ISSUE TITLE
[Request] consider using a different branch for the refactor 

### ISSUE THREAD

**Issue by kylo252** [kyazdani42/nvim-tree.lua#759]
First of all, thank you for all the amazing work you've been doing.

Please consider using a different branch for the refactor and push all the changes at once. I can still see there are about 20 global options still, just judging by the README, which judging by the current pace will mean another 20 or so breaking changes instead of one. 

Another recently pain point is trying to understand the difference between the old options and the new one: 

```yaml
- |update_focused_file.update_cwd|: update the root directory of the tree to the one
    of the folder containing the file if the file is not under the current root
    directory. Only relevant when |update_focused_file.enable| is `true`
    type: `boolean`
    default: `false`
```
vs

```yaml
|g:nvim_tree_respect_buf_cwd|             *g:nvim_tree_respect_buf_cwd*

Can be 0 or 1. 0 by default.
Will change cwd of nvim-tree to that of new buffer's when opening nvim-tree.
```

---

Or trying to see why the similar options aren't in the same scope:

```yaml
- |open_on_tab|: opens the tree automatically when switching tabpage or opening a new
  tabpage if the tree was previously open.
  type: `boolean`
  default: `false`
```  

vs

```yaml
|g:nvim_tree_quit_on_open|			*g:nvim_tree_quit_on_open*

Can be `0` or `1`. When `1`, will close the tree when a file is opened.
Applies to: `edit`, `vsplit`, `split`, `tabnew`.
Default is 0
```

I think it'll be easier to make sense of the options when the similar ones are actually grouped together, and probably help the transition in general.
